### ISSUE TITLE
error when i try to run first flutter application

### ISSUE THREAD

**Issue by massi04** [ZeroK-RTS/CrashReports#23562]
hello world!
So the console shows this : 
![image](https://user-images.githubusercontent.com/54027877/62979822-25472e00-be25-11e9-8d40-745a37fb9ad1.png)
and when i run the commande "flutter run" it shows this:
[flutter_01.log](https://github.com/ZeroK-RTS/CrashReports/files/3499046/flutter_01.log)

**Comment by GoogleFrog** [comment]
It looks like you have the wrong project.

**Comment by massi04** [comment]
> It looks like you have the wrong project.
what should I do? I followed the setup instructions step by step.I even looked into every youtube tuto and still cant find a solution.
It would be much appreciated if u help me find a solution
